CREATE DATABASE rss_feed_manager;

CREATE TABLE feeds (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  address VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT "0000-00-00 00:00:00",
  UNIQUE (name, address)
);